Contribute to app-i18n/fcitx-bamboo
gentoo-zh/overlay pull request #2654
Opened 2022-11-18 13:55 UTC by vuongtuha

2022-11-18 14:04 UTC, Universebenzene requested changes

2022-11-18 14:04 UTC, Universebenzene commented on app-i18n/fcitx-bamboo/metadata.xml
> +		<flag name="qt">Enable Qt for GUI configuration</flag>
`qt` flag is not appeared in your ebuild. No need to write this in metadata

However you defined a `go` flag in your ebuild without description. And I don't understand how this flag works

2022-11-18 14:04 UTC, Universebenzene commented on app-i18n/fcitx-bamboo/fcitx-bamboo-1.0.1.ebuild
> +	xdg_pkg_postinst
`xdg-utils.eclass` is not enough for this function. Use `xdg.eclass` instead

2022-11-18 14:08 UTC, Universebenzene commented on app-i18n/fcitx-bamboo/fcitx-bamboo-1.0.1.ebuild
> +		-DCMAKE_INSTALL_LIBDIR="${EPREFIX}/usr/$(get_libdir)"
This should be the default behavior of  `cmake.eclass`. I think you don't need to write the `src_configure` phase out

2022-11-18 14:17 UTC, vuongtuha commented
Thanks for your review. 1st of all, before creating this ebuild, I had to
wonder about how should I force the user to USE="+qt". I asked even
upstream that could I make it build without go-lang.
Then even before pulling this request, I hoped that someone could test my
build. And would you mind if I ask "is Telegram channel Gentoo-zh the place
to share about this? ". Or are you in this channel?
Sorry I don't know Chinese, but 1st I think I need somewhere to get the
answer to my question. Ofc, you decide what is suitable for your repo, it's
your permission. Maybe I need others' help to finish this ebuild.  If you
feel fine about this, just let me know. Thanks!

On Fri, Nov 18, 2022 at 9:04 PM 天苯 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In app-i18n/fcitx-bamboo/metadata.xml
> <https://github.com/microcai/gentoo-zh/pull/2654#discussion_r1026468156>:
>
> > @@ -0,0 +1,11 @@
>
> +<?xml version="1.0" encoding="UTF-8"?>
>
> +<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
>
> +<pkgmetadata>
>
> +	<maintainer type="person">
>
> +		***@***.***</email>
>
> +		<name>Vương Tử Hà</name>
>
> +	</maintainer>
>
> +	<use>
>
> +		<flag name="qt">Enable Qt for GUI configuration</flag>
>
>
> qt flag is not appeared in your ebuild. No need to write this in metadata
>
> However you defined a go flag in your ebuild without description. And I
> don't understand how this flag works
> ------------------------------
>
> In app-i18n/fcitx-bamboo/fcitx-bamboo-1.0.1.ebuild
> <https://github.com/microcai/gentoo-zh/pull/2654#discussion_r1026469131>:
>
> > +"
>
> +RDEPEND="${DEPEND}"
>
> +BDEPEND="
>
> +	dev-lang/go
>
> +	kde-frameworks/extra-cmake-modules
>
> +"
>
> +
>
> +src_configure() {
>
> +	local mycmakeargs=(
>
> +		-DCMAKE_INSTALL_LIBDIR="${EPREFIX}/usr/$(get_libdir)"
>
> +	)
>
> +	cmake_src_configure
>
> +}
>
> +
>
> +pkg_postinst() {
>
> +	xdg_pkg_postinst
>
>
> xdg-utils.eclass is not enough for this function. Use xdg.eclass instead
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/microcai/gentoo-zh/pull/2654#pullrequestreview-1186147369>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQWPAYWPM2KQD6WBTBLJPSLWI6EGDANCNFSM6AAAAAASEQRK44>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-18 14:25 UTC, Universebenzene commented
@vuongtuha 
> , before creating this ebuild, I had to wonder about how should I force the user to USE="+qt".

`qt` flag is not appeared in any conditions in your ebuild. Whether people enabled this flag or not will do nothing for your package.



> I asked even upstream that could I make it build without go-lang.

If this package really needs `dev-lang/go` for compiling, just write it in `BDEPEND` is enough. Defining a USE flag without any condition will do nothing.

2022-11-18 15:10 UTC, st0nie commented
@github-actions[bot] 改成inherit cmake xdg，然后go的依赖先去掉吧。pkg_postinst() 一整段也可以删掉

2022-11-18 15:15 UTC, Universebenzene commented
@ston-afk 以及metadata里的use desc也应该删了

2022-11-18 15:17 UTC, ston-afk commented
@Universebenzene 还得rebase一下（

2022-11-19 06:35 UTC, ston-afk commented
@github-actions[bot] DEPEND不应该包含configtool
src_configure()和pkg_postinst可以整个都删掉了，这是eclass的默认行文

2022-11-19 10:42 UTC, closed without merging