net-im/weixin-uos: support cmdline arguments
gentoo-zh/overlay pull request #2911
Opened 2023-02-15 01:24 UTC by st0nie

可以方便传electron的参数
Signed-off-by: ston [ston.jia@qq.com](mailto:ston.jia@qq.com)

2023-02-15 23:44 UTC, liangyongxiang commented
这个需要加revision吧？让现有用户都重装一遍

2023-02-16 09:36 UTC, microcai requested changes
对, 需要加 reversion

2023-02-16 10:29 UTC, st0nie commented
> 这个需要加revision吧？让现有用户都重装一遍

done

2023-02-16 11:14 UTC, liangyongxiang approved these changes

2023-02-16 14:14 UTC, microcai approved these changes
这次看起来不错 可以合并了

2023-02-16 14:14 UTC, microcai approved these changes
这次看起来不错 可以合并了

2023-02-16 14:16 UTC, merged