net-proxy/clash-meta: openrc support
gentoo-zh/overlay pull request #3191
Opened 2023-04-25 06:53 UTC by oatiz

@st0nie 麻烦 review 下

2023-04-25 07:56 UTC, aieu commented on net-proxy/clash-meta/clash-meta-1.14.3.ebuild
> +	if use systemd; then
https://devmanual.gentoo.org/general-concepts/use-flags/index.html#when-not-to-use-use-flags

2023-04-25 08:12 UTC, st0nie reviewed
能想办法用clash-meta的用户和组跑最好，如果那样的话，安装完毕后需要setcap一下，否则clash-meta是无法在openrc下开tun的，我建议在post_inst()里加上setcap cap_net_bind_service,cap_net_admin=+ep /path/to/clash-meta，不清楚在src_install里setcap后，安装后还是否可以生效

2023-04-25 08:26 UTC, oatiz commented
> 能想办法用clash-meta的用户和组跑最好，如果那样的话，安装完毕后需要setcap一下，否则clash-meta是无法在openrc下开tun的，我建议在post_inst()或者src_install()里加上setcap cap_net_bind_service,cap_net_admin=+ep /path/to/clash-meta，不清楚在src_install里setcap后，安装后还是否可以生效

可以的，等晚上回去我改下。顺便测测

2023-04-26 04:58 UTC, st0nie requested changes

2023-04-26 04:58 UTC, st0nie commented on net-proxy/clash-meta/clash-meta-1.14.3.ebuild
> +RDEPEND="${DEPEND}
看起来你systemd这个use似乎是没用上？

2023-04-26 06:14 UTC, oatiz commented
@st0nie @aieu @liangyongxiang @Universebenzene 

按照意见改好了，麻烦再review下

2023-04-26 06:15 UTC, liangyongxiang approved these changes

2023-04-26 06:19 UTC, st0nie approved these changes

2023-04-26 06:19 UTC, st0nie commented on net-proxy/clash-meta/clash-meta-1.14.3.ebuild
> +IUSE="+gvisor lwip systemd"
同上

2023-04-26 06:19 UTC, st0nie commented on net-proxy/clash-meta/metadata.xml
> +        <flag name="systemd">install provided systemd service</flag>
这个也得删了

2023-04-26 06:20 UTC, st0nie approved these changes

2023-04-26 06:29 UTC, st0nie approved these changes
应该没问题了

2023-04-26 06:44 UTC, aieu approved these changes

2023-04-26 06:48 UTC, merged