fcitx5/fcitx5: version bump to 5.0.4
gentoo-zh/overlay pull request #695
Opened 2021-01-28 12:58 UTC by liangyongxiang

- Use app-i18n/unicode-cldr instead of app-i18n/cldr-emoji-annotation

2021-01-28 13:19 UTC, liangyongxiang commented
fcitx5-diagnose会卡住，请先不要合并

2021-01-28 13:29 UTC, liangyongxiang commented
> fcitx5-diagnose会卡住，请先不要合并

不是卡住，是执行时间比较久

2021-01-30 14:01 UTC, wgjak47 requested changes

2021-01-30 14:01 UTC, wgjak47 commented on app-i18n/fcitx5-gtk/fcitx5-gtk-9999.ebuild
> +IUSE="+gtk2 +gtk3 +introspection +snooper"
the use of gtk4 could be saved here and set disabled for the future.

2021-01-30 14:25 UTC, merged

2021-01-30 20:02 UTC, liangyongxiang commented on app-i18n/fcitx5-configtool/fcitx5-configtool-5.0.2.ebuild
> +	KEYWORDS="~amd64 ~x86"
我没有测试过这个。我只是移动了代码的位置。

2021-01-30 20:04 UTC, liangyongxiang commented on app-i18n/fcitx5-gtk/fcitx5-gtk-9999.ebuild
> +IUSE="+gtk2 +gtk3 +introspection +snooper"
我是觉得gtk4的支持会在gentoo官方添加fcitx5的后面。（逃