x11-misc/ly:Ly - a TUI display manager
gentoo-zh/overlay pull request #890
Opened 2021-05-06 16:35 UTC by OriPoin

update ly-0.5.0 to ly-0.5.0-r1, use stable archives

2021-05-06 16:41 UTC, jian-lin requested changes

2021-05-06 16:41 UTC, jian-lin commented on x11-misc/ly/ly-0.5.0-r1.ebuild
> +                cp -r ${WORKDIR}/${_i}-master/* ${S}/sub/${_i}
一般要在最后加上 ` || die` https://devmanual.gentoo.org/ebuild-writing/error-handling/#the-die-function

2021-05-07 03:18 UTC, merged

2021-05-07 03:25 UTC, tlze commented
可以的话，不相关的修改放到不同的commit，以上隐藏修改了wps-office，不安全也不方便其他人维护。

2021-05-07 03:28 UTC, liangyongxiang commented
@tlze 他没有rebase，所以log上能看到他merge了我之前的wps-office得修改

2021-05-07 03:33 UTC, liangyongxiang commented
如果需要就revert吧。

2021-05-07 03:39 UTC, liangyongxiang commented
或者下次遇到这种就先不要合并。等他rebase。

2021-05-07 03:40 UTC, tlze commented
是的，这次修改都检查过，没发现问题才合并，上面只提示下。
这种情况以前也出现过。

2021-05-07 03:41 UTC, liangyongxiang commented
OK

2021-05-07 03:47 UTC, OriPoin commented
十分抱歉，是我用git不熟练。要不还是revert一下，我再去rebase。

2021-05-07 03:51 UTC, tlze commented
没事，不误伤其它ebuild就好，时刻记住：安全第一条，不要破坏别人的系统。共勉！

On Fri, May 7, 2021 at 11:48 AM Yachen ***@***.***> wrote:

> 十分抱歉，是我用git不熟练。要不还是revert一下，我再去rebase。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microcai/gentoo-zh/pull/890#issuecomment-834042577>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACQHW2MKH3XZACM7RA2XI3TMNPHVANCNFSM44HNQNYA>
> .
>

2021-05-07 04:40 UTC, jian-lin commented
> 十分抱歉，是我用git不熟练。要不还是revert一下，我再去rebase。

帮你找了个PR的教程 https://gist.github.com/Chaser324/ce0505fbed06b947d962